# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Logo')),
            ],
            options={
                'verbose_name': 'Logo',
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, help_text='write short and sweet description related to your title', null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='publish',
            field=models.BooleanField(default=False, help_text='check me to show this banner image in home page'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, help_text='Give beautiful title', max_length=50, null=True),
        ),
    ]
