# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160702_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 2, 11, 50, 49, 316264, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
