# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_logo_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(help_text='Write Full Name of Organization', max_length=140, verbose_name='organization Full Name')),
                ('address', models.CharField(help_text='eg. Sanepa, Lalitpur', max_length=140, verbose_name='Organization Full Adress')),
                ('country', models.CharField(help_text='Nepal', max_length=50)),
                ('phone', models.IntegerField()),
                ('phone_2', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('google_plus_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('pinterest_url', models.URLField(blank=True, null=True)),
                ('copyright', models.CharField(max_length=150)),
            ],
        ),
    ]
