# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='facbook_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='google_plus_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='instagram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='linkedin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='pinterest_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='twitter_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
        migrations.AddField(
            model_name='footer',
            name='youtube_icon',
            field=models.ImageField(blank=True, null=True, upload_to='Social Icon'),
        ),
    ]
