# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20160702_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingarea',
            name='publish',
            field=models.BooleanField(default=False, help_text='check me to show this in home page'),
        ),
    ]
