# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_workingarea_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Working Areas')),
                ('publish', models.BooleanField(default=False, help_text='check me to show this in home page')),
                ('created', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
