# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_recentwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Facebook, Twetter, Youtube', max_length=20, verbose_name='social Media Name')),
                ('url', models.URLField(help_text='https://www.facebook.com/pagename')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Social Media Icon')),
            ],
        ),
        migrations.DeleteModel(
            name='RecentWork',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facbook_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='google_plus_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='google_plus_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='pinterest_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='pinterest_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitter_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_icon',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='workingarea',
            name='recent_work',
            field=models.BooleanField(default=False, help_text='check me to display as recent work'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.CharField(help_text='2016 All right reserved By Organization Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Organization Email Adress'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Organization Email Adress'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone',
            field=models.IntegerField(verbose_name='Organization Phone Number'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='phone_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Organization Phone Number 2'),
        ),
    ]
